### ISSUE TITLE
preflight checklist the cluster

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1020]
- https://medium.com/better-programming/how-to-harden-your-kubernetes-cluster-for-production-7e47990efc2a
- https://blog.pipetail.io/posts/2020-05-04-most-common-mistakes-k8s/

Collecting from the articles above:

- [x] use managed k8s service
- [x] upgrade k8s automatically/frequently  -  created #1025 
- [x] Patch and Harden Your OS
  - 🔼 rely on AMI #1025 
- [x] Enforce RBAC
  - default for EKS
- [x] Use TLS for API server
  - default for EKS
- [x] Segregate Resources in Namespaces
  - yes, but less relevant as we don't hand out kubectl access
- [x] Control Pod to Pod Traffic
  - https://kubernetes.io/docs/concepts/services-networking/network-policies/
  - should ideally be implemented on a chart level
  - 🔼 created #1026 for reviewer and added to https://github.com/elifesciences/issues/issues/5713
- [x] Create Separate User Accounts
  - less relevant to us due to flux
  - consider as part of IAM role audits
- [x] Follow the Principle of Least Privilege
  - yay for flux
- [x] Frequently Rotate Infrastructure Credentials
  - 🔼 created https://github.com/elifesciences/issues/issues/5714
- [x] Use a Partitioned Approach to Secure Secrets
  - 🔼 created https://github.com/elifesciences/issues/issues/5715
  - [vault sidecar](https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/) probably solves this
  - how to [sealed secrets](https://github.com/bitnami-labs/sealed-secrets) address this?
- [x] Limit Resource Usage
  - we have default mem limits and default cpu and mem requests
  - no default cpu limit, see #1023 
- [x] Protect Your etcd Cluster Like a Treasure Vault
  - eks default
- [x] Control Container Privileges
  - https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  - eks runs by default with super permissive policy https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html
  - 🔼 created #1027
- [x] Enable Auditing
  - requires discussion re: log storage and logging reqs in general #1028
- [x] self anti-affinities for pods
  - 🔼  helm chart checklist
- [x] Not using the power of IAM/RBAC
  - 🔼  created https://github.com/elifesciences/issues/issues/5715
  - instead of loading s3/RDS credentials from env we can attach IAM roles to ServiceAccounts to achieve automatic rotation of credentials
  - https://blog.pipetail.io/posts/2020-04-13-more-eks-tips/
- [x] no poddisruptionbudget
  - 🔼  helm chart checklist
- [x] externalTrafficPolicy: Cluster
  - don't think this impacts us (yet)
- [x] using latest tag
  - libero scripts/github/retag-and-push.sh and renovatebot take care of this
- [x] pet clusters + stressing the control plane too much
  - control plane is done by eks
  - move to prod cluster will test how resilient/ephemeral our clusters can be
