### ISSUE TITLE
How to update core services on cluster safely

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1045]
## Background

An automated image update of the ingress controller ended in a crash loop due to too low memory limit which causes access to our services to break.

## Current state

Mission critical components (external-dns and ingress controller) are not automatically update by flux.

## ToDo

- [x] use renovatebot, codeowner etc to notify us of availabe updates?
- [x] documentation regarding strategy for core cluster components
- [x] pin chart version of critical infra
- [x] auto-update non-critical infra
- [x] test on test-cluster
- [x] apply to prod cluster

## critical infra services

- [x] external-dns
- [x] ingress-nginx

**Comment by erkannt** [comment]
@lsh-0 You should have been automatically been notified/assigned to some PRs generated by renovatebot upgrading 'system' deployments on the cluster.

I set this up to make upgrades to the 'system' services as painless as possible. You can find the documentation [here](https://github.com/elifesciences/elife-flux-cluster/blob/master/docs/infra-updates.md). Other non-system i.e. product services can adopt similar strategies if they like. For reviewer we are going with manually bumping the production chart.

Please let me know what you think or if I missed something.

**Comment by lsh-0** [comment]
> Hiya, would you mind taking a look at https://github.com/libero/reviewer/issues/1045 ?
Would appreciate your thought and if there is anything else I can do to make maintaining the cluster as pleasant as possible.

kubernetes and how to maintain a cluster is still quite alien to me. I'll be relying on your documentation for the meanwhile. 

@NuclearRedeye may want to add something
