### ISSUE TITLE
Dry-Run switch from xpub to reviewer and back

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1126]
Go for single switch, not gradual
- First switch by changing XPUB ELB to point at cluster ELB
- Later switch DNS to point directly at cluster LEB

Dry-run against xpub staging
- RDS (separate RDS and migration or use existing?)
- ELB switcheroo
- Test that a half finished-submission can be completed after the switch has happened (i.e. half done in xPub and half done in Reviewer)
- Dry-run rollback to xpub
- Rollback to snapshot of RDS

## Todo:

- [x] set up database migration in aws
- [x] investigate ability to make switch via ELB to prevent stale DNS
- [x] write playbook for switchover
- [x] set up s3 bucket in builder for reviewer
- [x] sync s3 buckets
- [x] check which domains are used by continuum e2e test
- [x] upgrade db via builder (after migration of staging has been completed)
- [x] remove `staging-libero-reviewer` bucket (old, unsure of origin)
- [ ] attempt copying data in reviewer back to xpub manually and document for worst case

##  Checks to perform:

- [x] half finished submissions in xpub can be completed in reviewer
- [x] ~~vice versa~~
- [x] ~~old dns resolution will redirect to reviewer~~ not easily doable, see notes
- [x] ~~switch back to xpub works~~ in case of switch back we will move data from reviewer to xpub manually
- [x] DNS TTL is short e.g. 60s

## Notes

- [Playbook/Notes](https://docs.google.com/document/d/1AefLeCQHjN3-ZvI9UkoZe1Yx5Bf0jfHRgk1VcBMXn10/edit?usp=sharing) in google doc
- can't redirect one ELB to another ELB  
  The only way to get that to to work would be to spin up an instance, attach it to the old elb, use instance to redirect to new elb. I'd therefore suggest to check if we can instead continue to receive traffic on xpub and keep the DB and S3 in sync while DNS propagates.
