### ISSUE TITLE
Integrate MECA to chart and umbrella tests

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1130]
Chart and staging env:

- [x] ingress in chart for /meca-result
- [x] add sftp and bucket envvar to chart
- [x] add sftp secret to staging deploy (ejp test env)

Umbrella repo:

- [x] add sftp container so that submission can handle when 'submit' button is clicked in browsertests
- [x] add envvars for meca stuff in umbrella compose file(s)
