### ISSUE TITLE
Storybook Deployment

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#301]
## Assumptions

- The `reviewer_client` Docker image can be used with a custom entrypoint to produce the Storybook static website
- This is a Libero deployment, because the Service Provider are an audience

## Tasks

- [x] Run the `reviewer_client` image in the build with the right command. This will create a container that will be stopped after the command terminates.
- [x] Copy (`docker cp`) the static website out of the container.
- [x] Push the static website on an S3 bucket.
  - [x] Create the S3 bucket in `libero/infrastructure`, apply to all environments.
  - [x] Put the credentials necessary for the push in the `libero/reviewer` Travis CI build.
- [x] Manual test that everything is publicly available.

**Comment by giorgiosironi** [comment]
Useful links:
- [Travis CI standard deployment to S3](https://docs.travis-ci.com/user/deployment/s3/)
- How we [extract files from a container in `pattern-library`](https://github.com/elifesciences/pattern-library/blob/93884dd76130718b78d0992085e3c401a7fafd6c/Jenkinsfile#L44-L49)
