### ISSUE TITLE
Trial Container Image Tagging Convention

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#631]
Following approval of https://github.com/libero/community/issues/36, implement for reviewer.

## Tasks/Questions to solve
- [x] tagging images with branch-sha
- [x] semver tagging
- [x] run integration tests on PR and master in umbrella
- [x] adjust ADR according to lessons learned
- [x] avoid rebuild of image upon semver tagging (pull master-sha) instead
- [x] validate

## Repos to cover

- [x] reviewer-submissions
- [x] reviewer-client
- [x] reviewer-mocks
- [x] continuum-adaptor
- [x] audit

## Notes

- moving usage of tagged images in reviewer umbrella repo to own issue

**Comment by erkannt** [comment]
Reviewer team has kindly agreed to use [libero/reviewer-submission](https://github.com/libero/reviewer-submission) to validate the adapted github workflows and new `push-image.sh`. Upon success this script will be moved into [libero/scripts](https://github.com/libero/scripts) for further rollout
