### ISSUE TITLE
Pin images for integration tests

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#695]
Definition of Done:

- [x] all images used in umbrella integration tests are pinned
- [x] bot makes PR and automerges upon new images on hub
- [x] reviewer team gets notified on failure

## Related

- https://github.com/elifesciences/issues/issues/5520

## Tasks

- [x] pin images in compose file in umbrella repo
- [x] setup renovatebot
- [x] slack notifications on failure
- [x] add renovatebot for component repos
- [x] determine strategy for tracking master/semver (branches, matrix job, if conditions)

**Comment by erkannt** [comment]
Struggling to set up tracking for our master-hash images. See https://github.com/libero/community/pull/38#issuecomment-608533584

**Comment by erkannt** [comment]
- Slack notification is not test, will keep an eye on it
- we appear to have a flaky test in umbrella, rerunning jobs gets them to pass...

**Comment by erkannt** [comment]
Renovate has stopped finding updates via docker hub. Need to investigate.

**Comment by erkannt** [comment]
Closing this as everything works in principle. But opened #758 to address the issue of libero images no longer being updated.
