### ISSUE TITLE
Extend existing browser tests

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#840]
- [x]  #849	Extend Dashboard Page Object
 - [x]  #850	Create Author Details page object
 - [x]  #851	Create the Files Page Object
 - [x]  #852	Create DetailsPage page object
 - [ ]  #853	Create EditorsPage page object
 - [ ]  #854	Create disclosure page page object
 - [ ]  #855	Create SurveyPage page object
 - [ ]  #856	Create General Page Object to handle navigation pane
 - [ ]  #857	Create Page objects for the static pages

**Comment by hdrury1** [comment]
Original xPub user stories: https://trello.com/b/NCBvfDJJ/elife-user-stories-for-xpub

**Comment by hdrury1** [comment]
@chugginselifesciences I've been hunting for a journey map for the initial submission wizard that captures the expected flow as this will help the developers design the Browser tests. I'm sure we did have one right at the beginning of the project?

**Comment by chugginselifesciences** [comment]
Most diagrams covered the QC process and beyond, and there might have been something quite simple related to login. I think this is the most detailed related to submission. But because it's a step-by-step wizard I've never mapped it out in much detail.

![initial-submissions-userflow](https://user-images.githubusercontent.com/41907215/80975322-de1d2500-8e19-11ea-8a79-bd85a704beed.png)
